src/Bugtinguish.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Bugtinguish.Models.Web;
using Microsoft.AspNetCore.Mvc;

namespace bugtinguish.Web.Controllers;
    
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
       _logger = logger; 
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult About()
    {
        return View();
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/Bugtinguish.Web/Controllers/TicketController.cs
using System.Diagnostics;
using Bugtinguish.Models.Web;
using Bugtinguish.Models.Shared;
using Microsoft.AspNetCore.Mvc;

namespace bugtinguish.Web.Controllers;
    
public class TicketController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public TicketController(ILogger<HomeController> logger)
    {
       _logger = logger; 
    }

    public IActionResult Index()
    {
        List<TicketOverviewModel> tickets = new();
        for (int i = 0; i < 10; i++)
        {
            tickets.Add(new()
            {
                Id = Guid.NewGuid(),
                Number = i,
                Tracker = "New",
                Created = DateTime.Now.ToShortDateString(),
                Assignee = "Jean Patrick Kocherscheidt",
                Progress = 0,
                Description = "A first glimpse of how tickets should look",
            });
        }

        return View(tickets);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/Bugtinguish.Web/Views/Home/About.cshtml
@{
ViewBag.Title = "About";
}

<p>This piece of software has been built with ASP.NET Core on version .NET 8.0</p>
<p>Libraries used:</p>
<ul>
    <li>libman</li>
    <li>jQuery 3.6.0</li>
</ul>

<p>You can freely change this software and redistribute to your liking.</p>

src/Bugtinguish.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<p>@ViewBag.Title</p>

src/Bugtinguish.Web/Views/Home/TrackerForm.cshtml
@{
    ViewBag.Title = "Tracker";
}
@section Scripts {
    <script src="~/scripts/jquery-validation/jquery.validation.min.js"></script>
    <script src="~/scripts/jquery-validation-unobtrusive/jquery.validation.unobtrusive.min.js"></script>
}

src/Bugtinguish.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <title>Bugtinguish: @ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/styles.css" />
</head>

<body>
    <header>Welcome to Bugtinguish</header>
    <section>
        <h2>@ViewBag.Title</h2>
        <menu>
            <ul>
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Home" asp-action="About">About</a></li>
                <li><a asp-controller="Ticket" asp-action="Index">Tickets</a></li>
            </ul>
        </menu>
        @RenderBody()
    </section>
    <footer>Copyleft 2024 Jean Patrick Kocherscheidt</footer>

    <script src="~/scripts/jquery/dist/jquery.min.js"></script>
    <script src="~/js/index.js"></script>

    @RenderSection("Scripts", false)
</body>

</html>

src/Bugtinguish.Web/Views/Ticket/Index.cshtml
@{
ViewBag.Title = "Ticket overview";
}

@model IReadOnlyCollection<TicketOverviewModel>

    <p>@ViewBag.Title</p>

    <table>
        <tr>
            <th>Number</th>
            <th>Tracker</th>
            <th>Assignee</th>
            <th>Created</th>
            <th>Description</th>
            <th>Progress</th>
            <th></th>
        </tr>
        @foreach (var ticket in Model)
        {
        <tr>
            <td>@ticket.Number</td>
            <td>@ticket.Tracker</td>
            <td>@ticket.Assignee</td>
            <td>@ticket.Created</td>
            <td>@ticket.Description</td>
            <td>@ticket.Progress</td>
            <td>Action buttons</td>
        </tr>
        }
    </table>